import type { Candidate, Job, StaffMember } from '@/types';

// Mock data — dynamic `postedAt` dates keep listings feeling fresh in dev without
// requiring maintenance. Will be replaced by Supabase-backed data in a later phase.
function daysAgo(n: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Policy Advisor',
    organisation: 'Norfolk County Council',
    location: 'Norwich',
    region: 'Norfolk',
    salary: '£52,000 – £61,000',
    salaryMin: 52000,
    salaryMax: 61000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Shape and deliver strategic policy across a large county authority, working directly with senior leadership and elected members.',
    postedAt: daysAgo(6),
  },
  {
    id: 'job-2',
    title: 'Social Worker – Children & Families',
    organisation: 'Suffolk County Council',
    location: 'Ipswich',
    region: 'Suffolk',
    salary: '£38,500 – £44,200',
    salaryMin: 38500,
    salaryMax: 44200,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Join an Ofsted-rated Good service supporting children and families through assessment, intervention and ongoing casework.',
    postedAt: daysAgo(8),
  },
  {
    id: 'job-3',
    title: 'Procurement Manager',
    organisation: 'Cambridgeshire County Council',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£48,000 – £55,000',
    salaryMin: 48000,
    salaryMax: 55000,
    contractType: 'Interim',
    sector: 'Local government',
    description:
      'Lead a programme of high-value public procurement across works, goods and services on a twelve-month interim engagement.',
    postedAt: daysAgo(10),
  },
  {
    id: 'job-4',
    title: 'Planning Officer',
    organisation: 'Chelmsford City Council',
    location: 'Chelmsford',
    region: 'Essex',
    salary: '£34,000 – £40,000',
    salaryMin: 34000,
    salaryMax: 40000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Manage a varied caseload of residential and commercial planning applications in one of the East of England’s fastest-growing districts.',
    postedAt: daysAgo(12),
  },
  {
    id: 'job-5',
    title: 'Data Analyst – Public Health',
    organisation: 'NHS East of England',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£42,000 – £49,000',
    salaryMin: 42000,
    salaryMax: 49000,
    contractType: 'Contract',
    sector: 'NHS',
    description:
      'Twelve-month contract supporting a regional public health team to turn data into insight and commissioning decisions.',
    postedAt: daysAgo(15),
  },
  {
    id: 'job-6',
    title: 'Head of Communications',
    organisation: 'Hertfordshire County Council',
    location: 'Hertford',
    region: 'Hertfordshire',
    salary: '£65,000 – £74,000',
    salaryMin: 65000,
    salaryMax: 74000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead internal and external communications for a high-profile county authority, reporting into the Chief Executive.',
    postedAt: daysAgo(17),
  },
  {
    id: 'job-7',
    title: 'Commissioning Lead – Adult Social Care',
    organisation: 'Essex County Council',
    location: 'Chelmsford',
    region: 'Essex',
    salary: '£55,000 – £62,000',
    salaryMin: 55000,
    salaryMax: 62000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Oversee strategic commissioning for adult social care services across one of the largest authorities in the East of England.',
    postedAt: daysAgo(18),
  },
  {
    id: 'job-8',
    title: 'Housing Options Officer',
    organisation: 'Luton Borough Council',
    location: 'Luton',
    region: 'Bedfordshire',
    salary: '£32,000 – £38,000',
    salaryMin: 32000,
    salaryMax: 38000,
    contractType: 'Permanent',
    sector: 'Housing',
    description:
      'Support residents facing homelessness with assessments, prevention advice and temporary accommodation placements.',
    postedAt: daysAgo(19),
  },
  {
    id: 'job-9',
    title: 'Transport Planner',
    organisation: 'Buckinghamshire Council',
    location: 'Aylesbury',
    region: 'Buckinghamshire',
    salary: '£44,000 – £52,000',
    salaryMin: 44000,
    salaryMax: 52000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Develop and appraise transport schemes including active travel, public transport and major highway interventions.',
    postedAt: daysAgo(21),
  },
  {
    id: 'job-10',
    title: 'Head of Regeneration',
    organisation: 'Peterborough City Council',
    location: 'Peterborough',
    region: 'Cambridgeshire',
    salary: '£72,000 – £82,000',
    salaryMin: 72000,
    salaryMax: 82000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead a multidisciplinary regeneration team driving town-centre renewal, housing delivery and inward investment.',
    postedAt: daysAgo(23),
  },
  {
    id: 'job-11',
    title: 'Family Support Worker',
    organisation: 'Bedford Borough Council',
    location: 'Bedford',
    region: 'Bedfordshire',
    salary: '£28,000 – £33,500',
    salaryMin: 28000,
    salaryMax: 33500,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Work with families on early help plans, building resilience and reducing the need for statutory intervention.',
    postedAt: daysAgo(25),
  },
  {
    id: 'job-12',
    title: 'Emergency Planning Officer',
    organisation: 'Norfolk Fire & Rescue Service',
    location: 'Norwich',
    region: 'Norfolk',
    salary: '£36,000 – £42,000',
    salaryMin: 36000,
    salaryMax: 42000,
    contractType: 'Permanent',
    sector: 'Emergency services',
    description:
      'Coordinate civil contingencies planning, training exercises and multi-agency incident response across the county.',
    postedAt: daysAgo(27),
  },
  {
    id: 'job-13',
    title: 'Principal Auditor',
    organisation: 'Department for Work and Pensions',
    location: 'London',
    region: 'National',
    salary: '£58,000 – £68,000',
    salaryMin: 58000,
    salaryMax: 68000,
    contractType: 'Permanent',
    sector: 'Central government',
    description:
      'Lead complex internal audit engagements across a major central government department, reporting to audit committee.',
    postedAt: daysAgo(29),
  },
  {
    id: 'job-14',
    title: 'SENCo (Special Educational Needs Coordinator)',
    organisation: 'Hertfordshire Schools Partnership',
    location: 'St Albans',
    region: 'Hertfordshire',
    salary: '£42,000 – £50,000',
    salaryMin: 42000,
    salaryMax: 50000,
    contractType: 'Permanent',
    sector: 'Education',
    description:
      'Coordinate SEND provision across a cluster of primary schools, supporting pupils, families and classroom teams.',
    postedAt: daysAgo(30),
  },
  {
    id: 'job-15',
    title: 'Environmental Health Officer',
    organisation: 'Colchester City Council',
    location: 'Colchester',
    region: 'Essex',
    salary: '£34,500 – £40,000',
    salaryMin: 34500,
    salaryMax: 40000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Investigate complaints, conduct inspections and deliver public protection work across food safety and licensing.',
    postedAt: daysAgo(5),
  },
  {
    id: 'job-16',
    title: 'Cyber Security Lead',
    organisation: 'Cabinet Office',
    location: 'London / Remote',
    region: 'National',
    salary: '£68,000 – £82,000',
    salaryMin: 68000,
    salaryMax: 82000,
    contractType: 'Permanent',
    sector: 'Central government',
    description:
      'Lead a team securing critical government services, driving threat modelling, incident response and assurance.',
    postedAt: daysAgo(11),
  },
  {
    id: 'job-17',
    title: 'Nurse Practitioner',
    organisation: 'Cambridge University Hospitals NHS',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£45,000 – £55,000',
    salaryMin: 45000,
    salaryMax: 55000,
    contractType: 'Permanent',
    sector: 'NHS',
    description:
      'Join a multidisciplinary team delivering advanced clinical care in a leading university teaching hospital.',
    postedAt: daysAgo(9),
  },
  {
    id: 'job-18',
    title: 'Customer Services Manager',
    organisation: 'Watford Borough Council',
    location: 'Watford',
    region: 'Hertfordshire',
    salary: '£42,000 – £48,000',
    salaryMin: 42000,
    salaryMax: 48000,
    contractType: 'Temporary',
    sector: 'Local government',
    description:
      'Six-month temporary assignment to stabilise and improve a busy frontline customer services function.',
    postedAt: daysAgo(3),
  },
  {
    id: 'job-19',
    title: 'Head of Finance',
    organisation: 'Milton Keynes Council',
    location: 'Milton Keynes',
    region: 'Buckinghamshire',
    salary: '£78,000 – £92,000',
    salaryMin: 78000,
    salaryMax: 92000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead corporate finance, budget setting and medium-term financial strategy for a unitary authority.',
    postedAt: daysAgo(4),
  },
  {
    id: 'job-20',
    title: 'Business Analyst',
    organisation: 'Suffolk Constabulary',
    location: 'Ipswich',
    region: 'Suffolk',
    salary: '£40,000 – £46,000',
    salaryMin: 40000,
    salaryMax: 46000,
    contractType: 'Interim',
    sector: 'Emergency services',
    description:
      'Interim analyst role supporting a force-wide programme to modernise frontline digital tooling.',
    postedAt: daysAgo(7),
  },
];

export const mockStaff: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Amara Okafor',
    title: 'Director of Public Sector',
    blurb:
      'Fifteen years placing senior policy and strategy leaders across UK local and central government.',
    yearsExperience: 15,
    qualification: 'MCIPD',
    area: 'National',
  },
  {
    id: 'staff-2',
    name: 'Rhys Llewellyn',
    title: 'Principal Consultant – Social Care',
    blurb:
      'Specialist in permanent and interim social care recruitment, with a focus on children and families.',
    yearsExperience: 11,
    qualification: 'REC CertRP',
    area: 'North & Midlands',
  },
  {
    id: 'staff-3',
    name: 'Hannah Patel',
    title: 'Senior Consultant – Planning & Regeneration',
    blurb:
      'Partners with councils and combined authorities to recruit planners, regeneration and housing professionals.',
    yearsExperience: 8,
    qualification: 'BA (Hons) Urban Planning',
    area: 'South East',
  },
  {
    id: 'staff-4',
    name: 'Daniel Ferreira',
    title: 'Consultant – Data & Digital',
    blurb:
      'Focused on data, digital and technology roles across public health, transport and central government.',
    yearsExperience: 6,
    qualification: 'BSc Computer Science',
    area: 'London & Remote',
  },
];

// Placeholder candidate showcase — all blurbs/bios strictly anonymised.
// No names, photos, contact details, or identifying employers. Client approval pending.
export const mockCandidates: Candidate[] = [
  {
    id: 'PSC-0042',
    roleTitle: 'Senior Planning Consultant',
    roleType: 'Planning',
    shortBlurb:
      'Chartered planner with a track record in complex residential and mixed-use applications across the home counties.',
    fullBio:
      'A chartered town planner with over a decade of experience guiding major schemes through determination, appeal and post-consent delivery. Brings strong client-facing and member-briefing skills, and has acted as lead planner on several £50m+ regeneration projects. Known for robust policy analysis and a pragmatic approach to viability. Looking for a senior in-house role or a specialist consultancy position within reach of the South East.',
    yearsExperience: 12,
    region: 'South East',
    qualifications: ['MRTPI', 'BA (Hons) Town Planning'],
    specialisms: ['Development management', 'Major applications', 'Appeals'],
    contractTypeSought: 'Permanent',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0057',
    roleTitle: 'Interim Head of Regeneration',
    roleType: 'Regeneration',
    shortBlurb:
      'Programme-level regeneration leader used to standing up teams quickly and delivering town-centre transformation at pace.',
    fullBio:
      'A senior regeneration professional with eighteen years across combined authorities and unitary councils in the East of England. Led multi-million pound Levelling Up and Towns Fund programmes from bid through to delivery. Comfortable managing elected-member scrutiny, private sector partners and cross-departmental teams. Seeking an interim engagement where they can add structure and pace to an existing programme.',
    yearsExperience: 18,
    region: 'East of England',
    qualifications: ['MRTPI', 'PRINCE2 Practitioner'],
    specialisms: ['Programme leadership', 'Funding bids', 'Stakeholder management'],
    contractTypeSought: 'Interim',
    availability: '4 weeks notice',
  },
  {
    id: 'PSC-0063',
    roleTitle: 'Social Worker – Children & Families',
    roleType: 'Social Care',
    shortBlurb:
      "Experienced child protection practitioner with a calm, evidence-led approach and a strong record in complex cases.",
    fullBio:
      "A registered social worker with six years in statutory children's services, currently carrying a mixed caseload including child protection and looked-after children. Known for high-quality assessments, clear written work and effective collaboration with partner agencies. Has mentored newly qualified colleagues and contributed to team learning reviews. Open to permanent moves within the North and Midlands.",
    yearsExperience: 6,
    region: 'North & Midlands',
    qualifications: ['BA (Hons) Social Work', 'Social Work England registered'],
    specialisms: ['Child protection', 'Looked-after children', 'Assessment'],
    contractTypeSought: 'Permanent',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0071',
    roleTitle: 'Policy Officer',
    roleType: 'Policy',
    shortBlurb:
      'Early-career policy professional with experience in central government and a sharp analytical background.',
    fullBio:
      'A policy officer with three years in a Whitehall department, contributing to submissions, consultation responses and ministerial briefings. Comfortable turning complex evidence into clear, decision-ready products and briefing senior officials at short notice. Strong interest in economic and labour-market policy. Looking for a mid-level move into local or combined-authority strategy.',
    yearsExperience: 3,
    region: 'London',
    qualifications: ['MA Public Policy', 'BA (Hons) Economics'],
    specialisms: ['Policy analysis', 'Consultation', 'Ministerial submissions'],
    contractTypeSought: 'Permanent',
    availability: '2 weeks notice',
  },
  {
    id: 'PSC-0084',
    roleTitle: 'Adult Social Care Commissioning Lead',
    roleType: 'Commissioning',
    shortBlurb:
      'Strategic commissioner with deep experience in adults pathways, market shaping and high-value tender oversight.',
    fullBio:
      'Fifteen years in public sector commissioning, most recently leading adult social care contracts with an annual spend exceeding £80m. Delivered successful re-procurements of home care and supported-living frameworks, and led market-shaping work following the national fair-cost-of-care exercise. Brings a pragmatic, relationship-based approach to provider engagement. Available for interim engagements immediately.',
    yearsExperience: 15,
    region: 'South East',
    qualifications: ['CMI Level 7 Strategic Management', 'BA (Hons) Social Policy'],
    specialisms: ['Adult social care', 'Market shaping', 'Procurement'],
    contractTypeSought: 'Interim',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0088',
    roleTitle: 'Director of Adult Social Care',
    roleType: 'Social Care',
    shortBlurb:
      'Executive social care leader with statutory DASS experience across two authorities and a reputation for turnaround.',
    fullBio:
      'A chief officer with twenty-two years in adult social care, including seven as a statutory Director of Adult Social Services across two authorities. Led successful CQC-style assurance preparation and delivered balanced budgets against a rising demand profile. Comfortable working closely with ICB partners and trusted by members. Open to permanent DASS opportunities nationally following the end of the current term.',
    yearsExperience: 22,
    region: 'National',
    qualifications: ['Social Work England registered', 'MSc Social Policy'],
    specialisms: ['DASS leadership', 'ICB partnerships', 'Assurance'],
    contractTypeSought: 'Permanent',
    availability: '3 months notice',
  },
  {
    id: 'PSC-0092',
    roleTitle: 'Transport Planner',
    roleType: 'Planning',
    shortBlurb:
      'Mid-weight transport planner with a strong background in active travel and major highways schemes.',
    fullBio:
      'Seven years in transport planning, delivering Local Transport Plan evidence bases, active travel schemes and major junction upgrades. Comfortable working with modelling teams and translating technical outputs for member briefings. Recently led the business case for a multi-million pound active travel programme successfully secured through Active Travel England. Open to permanent roles across the East of England.',
    yearsExperience: 7,
    region: 'East of England',
    qualifications: ['MSc Transport Planning', 'MCIHT'],
    specialisms: ['Active travel', 'Business cases', 'Highways'],
    contractTypeSought: 'Permanent',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0101',
    roleTitle: 'Executive Headteacher',
    roleType: 'Education Leadership',
    shortBlurb:
      'Executive head across a small primary federation with strong Ofsted outcomes and MAT partnership experience.',
    fullBio:
      'A serving executive headteacher leading a federation of three primary schools, all graded Good or better at their most recent inspections. Brings deep experience of school improvement, finance and governance, and has supported partner schools through federation and MAT processes. Interested in CEO-track leadership in a small-to-medium multi-academy trust, or a strategic education role within local government.',
    yearsExperience: 16,
    region: 'South East',
    qualifications: ['NPQH', 'QTS', 'MA Education'],
    specialisms: ['School improvement', 'MAT leadership', 'Governance'],
    contractTypeSought: 'Permanent',
    availability: 'Summer 2026',
  },
  {
    id: 'PSC-0108',
    roleTitle: 'Senior Procurement Manager',
    roleType: 'Procurement',
    shortBlurb:
      'MCIPS-qualified procurement lead with strong central-government framework experience across digital and estates.',
    fullBio:
      'Eleven years delivering complex public procurement, most recently for a major central government department. Strong track record running OJEU/Find-a-Tender processes on digital, professional services and estates categories. Known for building collaborative relationships with suppliers while maintaining tight commercial oversight. Available for interim assignments nationally from next month.',
    yearsExperience: 11,
    region: 'National',
    qualifications: ['MCIPS', 'Contract Management Level 5'],
    specialisms: ['Digital procurement', 'Professional services', 'Frameworks'],
    contractTypeSought: 'Interim',
    availability: '4 weeks notice',
  },
  {
    id: 'PSC-0115',
    roleTitle: 'Emergency Planning Manager',
    roleType: 'Emergency Services',
    shortBlurb:
      'Resilience professional with LRF leadership experience and a calm head in multi-agency incident response.',
    fullBio:
      'Fourteen years in civil contingencies planning across a metropolitan authority and a blue-light service. Chaired multi-agency working groups on flood, cyber and pandemic planning, and led debriefs following two recent regional incidents. Recognised by peers as a pragmatic and collaborative leader. Seeking a permanent strategic role that combines planning, response and community resilience.',
    yearsExperience: 14,
    region: 'London',
    qualifications: ['BCMS Level 6', 'ILM Level 5 Leadership'],
    specialisms: ['LRF leadership', 'Multi-agency exercises', 'Debriefs'],
    contractTypeSought: 'Permanent',
    availability: '6 weeks notice',
  },
  {
    id: 'PSC-0122',
    roleTitle: 'Housing Strategy Lead',
    roleType: 'Housing',
    shortBlurb:
      'Housing strategy specialist with deep experience on local plans, HRA business planning and tenant engagement.',
    fullBio:
      'Nine years across strategic housing, tenancy services and housing needs within a large metropolitan authority. Led the refresh of the housing strategy and contributed to the authority’s most recent Local Plan. Comfortable with member committees and tenant panels alike, and strong on data-led needs analysis. Open to contract work to stabilise an existing team.',
    yearsExperience: 9,
    region: 'North & Midlands',
    qualifications: ['CIH Level 5', 'BA (Hons) Housing Studies'],
    specialisms: ['Housing strategy', 'HRA', 'Tenant engagement'],
    contractTypeSought: 'Contract',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0127',
    roleTitle: 'Senior Finance Business Partner',
    roleType: 'Finance',
    shortBlurb:
      'CIPFA-qualified finance lead with experience business-partnering adult social care, capital and corporate portfolios.',
    fullBio:
      'A CIPFA-qualified finance professional with thirteen years across two upper-tier authorities. Currently business-partnering adult social care, leading medium-term financial planning and budget monitoring against demand-led pressures. Recently supported an external peer review of the MTFS. Open to permanent senior roles across the South East.',
    yearsExperience: 13,
    region: 'South East',
    qualifications: ['CIPFA qualified', 'BA (Hons) Accounting & Finance'],
    specialisms: ['MTFS', 'Adult social care finance', 'Capital programmes'],
    contractTypeSought: 'Permanent',
    availability: '1 month notice',
  },
  {
    id: 'PSC-0133',
    roleTitle: 'Regeneration Project Manager',
    roleType: 'Regeneration',
    shortBlurb:
      'Project manager delivering town-centre regeneration schemes end-to-end, from funding bid through construction hand-back.',
    fullBio:
      'Five years in regeneration project management, most recently delivering a Levelling Up-funded public realm scheme in a coastal market town. Comfortable leading a matrixed team of planners, engineers and quantity surveyors, and managing elected-member expectations across programme delivery. Looking for a contract role to bridge into their next permanent regeneration move.',
    yearsExperience: 5,
    region: 'South West',
    qualifications: ['APM PMQ', 'BA (Hons) Urban Studies'],
    specialisms: ['Public realm', 'Levelling Up delivery', 'Stakeholder management'],
    contractTypeSought: 'Contract',
    availability: 'Immediately',
  },
  {
    id: 'PSC-0140',
    roleTitle: 'Principal Social Worker (Adults)',
    roleType: 'Social Care',
    shortBlurb:
      'AMHP-qualified principal social worker with a strong record in practice development and safeguarding leadership.',
    fullBio:
      "Nineteen years in adult social care, including seven in Principal Social Worker roles. Led authority-wide practice development following the implementation of the Liberty Protection Safeguards, and oversaw the response to two high-profile safeguarding adults reviews. Approved Mental Health Professional with continued operational rota involvement. Open to permanent roles across the East of England.",
    yearsExperience: 19,
    region: 'East of England',
    qualifications: ['AMHP', 'Social Work England registered', 'MSW'],
    specialisms: ['Practice leadership', 'Safeguarding', 'Mental health'],
    contractTypeSought: 'Permanent',
    availability: '12 weeks notice',
  },
  {
    id: 'PSC-0148',
    roleTitle: 'Central Government Policy Advisor',
    roleType: 'Policy',
    shortBlurb:
      'Fast Stream-trained policy advisor with submissions, strategy and delivery experience across two departments.',
    fullBio:
      'Eight years of central government experience, completing the Civil Service Fast Stream and progressing through economic and labour-market policy posts. Has led work on a national strategy document published in 2024, and managed a cross-department review of a £100m+ programme. Looking for an interim engagement supporting a combined authority or devolved body during a period of strategic change.',
    yearsExperience: 8,
    region: 'National',
    qualifications: ['MPA', 'Civil Service Fast Stream'],
    specialisms: ['Strategy', 'Cross-government programmes', 'Economic policy'],
    contractTypeSought: 'Interim',
    availability: '4 weeks notice',
  },
];
