import type { Job, StaffMember } from '@/types';

// Mock data — dynamic `postedAt` dates keep listings feeling fresh in dev without
// requiring maintenance. Will be replaced by Supabase-backed data in a later phase.
function daysAgo(n: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Policy Advisor',
    organisation: 'Norfolk County Council',
    location: 'Norwich',
    region: 'Norfolk',
    salary: '£52,000 – £61,000',
    salaryMin: 52000,
    salaryMax: 61000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Shape and deliver strategic policy across a large county authority, working directly with senior leadership and elected members.',
    postedAt: daysAgo(6),
  },
  {
    id: 'job-2',
    title: 'Social Worker – Children & Families',
    organisation: 'Suffolk County Council',
    location: 'Ipswich',
    region: 'Suffolk',
    salary: '£38,500 – £44,200',
    salaryMin: 38500,
    salaryMax: 44200,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Join an Ofsted-rated Good service supporting children and families through assessment, intervention and ongoing casework.',
    postedAt: daysAgo(8),
  },
  {
    id: 'job-3',
    title: 'Procurement Manager',
    organisation: 'Cambridgeshire County Council',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£48,000 – £55,000',
    salaryMin: 48000,
    salaryMax: 55000,
    contractType: 'Interim',
    sector: 'Local government',
    description:
      'Lead a programme of high-value public procurement across works, goods and services on a twelve-month interim engagement.',
    postedAt: daysAgo(10),
  },
  {
    id: 'job-4',
    title: 'Planning Officer',
    organisation: 'Chelmsford City Council',
    location: 'Chelmsford',
    region: 'Essex',
    salary: '£34,000 – £40,000',
    salaryMin: 34000,
    salaryMax: 40000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Manage a varied caseload of residential and commercial planning applications in one of the East of England’s fastest-growing districts.',
    postedAt: daysAgo(12),
  },
  {
    id: 'job-5',
    title: 'Data Analyst – Public Health',
    organisation: 'NHS East of England',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£42,000 – £49,000',
    salaryMin: 42000,
    salaryMax: 49000,
    contractType: 'Contract',
    sector: 'NHS',
    description:
      'Twelve-month contract supporting a regional public health team to turn data into insight and commissioning decisions.',
    postedAt: daysAgo(15),
  },
  {
    id: 'job-6',
    title: 'Head of Communications',
    organisation: 'Hertfordshire County Council',
    location: 'Hertford',
    region: 'Hertfordshire',
    salary: '£65,000 – £74,000',
    salaryMin: 65000,
    salaryMax: 74000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead internal and external communications for a high-profile county authority, reporting into the Chief Executive.',
    postedAt: daysAgo(17),
  },
  {
    id: 'job-7',
    title: 'Commissioning Lead – Adult Social Care',
    organisation: 'Essex County Council',
    location: 'Chelmsford',
    region: 'Essex',
    salary: '£55,000 – £62,000',
    salaryMin: 55000,
    salaryMax: 62000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Oversee strategic commissioning for adult social care services across one of the largest authorities in the East of England.',
    postedAt: daysAgo(18),
  },
  {
    id: 'job-8',
    title: 'Housing Options Officer',
    organisation: 'Luton Borough Council',
    location: 'Luton',
    region: 'Bedfordshire',
    salary: '£32,000 – £38,000',
    salaryMin: 32000,
    salaryMax: 38000,
    contractType: 'Permanent',
    sector: 'Housing',
    description:
      'Support residents facing homelessness with assessments, prevention advice and temporary accommodation placements.',
    postedAt: daysAgo(19),
  },
  {
    id: 'job-9',
    title: 'Transport Planner',
    organisation: 'Buckinghamshire Council',
    location: 'Aylesbury',
    region: 'Buckinghamshire',
    salary: '£44,000 – £52,000',
    salaryMin: 44000,
    salaryMax: 52000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Develop and appraise transport schemes including active travel, public transport and major highway interventions.',
    postedAt: daysAgo(21),
  },
  {
    id: 'job-10',
    title: 'Head of Regeneration',
    organisation: 'Peterborough City Council',
    location: 'Peterborough',
    region: 'Cambridgeshire',
    salary: '£72,000 – £82,000',
    salaryMin: 72000,
    salaryMax: 82000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead a multidisciplinary regeneration team driving town-centre renewal, housing delivery and inward investment.',
    postedAt: daysAgo(23),
  },
  {
    id: 'job-11',
    title: 'Family Support Worker',
    organisation: 'Bedford Borough Council',
    location: 'Bedford',
    region: 'Bedfordshire',
    salary: '£28,000 – £33,500',
    salaryMin: 28000,
    salaryMax: 33500,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Work with families on early help plans, building resilience and reducing the need for statutory intervention.',
    postedAt: daysAgo(25),
  },
  {
    id: 'job-12',
    title: 'Emergency Planning Officer',
    organisation: 'Norfolk Fire & Rescue Service',
    location: 'Norwich',
    region: 'Norfolk',
    salary: '£36,000 – £42,000',
    salaryMin: 36000,
    salaryMax: 42000,
    contractType: 'Permanent',
    sector: 'Emergency services',
    description:
      'Coordinate civil contingencies planning, training exercises and multi-agency incident response across the county.',
    postedAt: daysAgo(27),
  },
  {
    id: 'job-13',
    title: 'Principal Auditor',
    organisation: 'Department for Work and Pensions',
    location: 'London',
    region: 'National',
    salary: '£58,000 – £68,000',
    salaryMin: 58000,
    salaryMax: 68000,
    contractType: 'Permanent',
    sector: 'Central government',
    description:
      'Lead complex internal audit engagements across a major central government department, reporting to audit committee.',
    postedAt: daysAgo(29),
  },
  {
    id: 'job-14',
    title: 'SENCo (Special Educational Needs Coordinator)',
    organisation: 'Hertfordshire Schools Partnership',
    location: 'St Albans',
    region: 'Hertfordshire',
    salary: '£42,000 – £50,000',
    salaryMin: 42000,
    salaryMax: 50000,
    contractType: 'Permanent',
    sector: 'Education',
    description:
      'Coordinate SEND provision across a cluster of primary schools, supporting pupils, families and classroom teams.',
    postedAt: daysAgo(30),
  },
  {
    id: 'job-15',
    title: 'Environmental Health Officer',
    organisation: 'Colchester City Council',
    location: 'Colchester',
    region: 'Essex',
    salary: '£34,500 – £40,000',
    salaryMin: 34500,
    salaryMax: 40000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Investigate complaints, conduct inspections and deliver public protection work across food safety and licensing.',
    postedAt: daysAgo(5),
  },
  {
    id: 'job-16',
    title: 'Cyber Security Lead',
    organisation: 'Cabinet Office',
    location: 'London / Remote',
    region: 'National',
    salary: '£68,000 – £82,000',
    salaryMin: 68000,
    salaryMax: 82000,
    contractType: 'Permanent',
    sector: 'Central government',
    description:
      'Lead a team securing critical government services, driving threat modelling, incident response and assurance.',
    postedAt: daysAgo(11),
  },
  {
    id: 'job-17',
    title: 'Nurse Practitioner',
    organisation: 'Cambridge University Hospitals NHS',
    location: 'Cambridge',
    region: 'Cambridgeshire',
    salary: '£45,000 – £55,000',
    salaryMin: 45000,
    salaryMax: 55000,
    contractType: 'Permanent',
    sector: 'NHS',
    description:
      'Join a multidisciplinary team delivering advanced clinical care in a leading university teaching hospital.',
    postedAt: daysAgo(9),
  },
  {
    id: 'job-18',
    title: 'Customer Services Manager',
    organisation: 'Watford Borough Council',
    location: 'Watford',
    region: 'Hertfordshire',
    salary: '£42,000 – £48,000',
    salaryMin: 42000,
    salaryMax: 48000,
    contractType: 'Temporary',
    sector: 'Local government',
    description:
      'Six-month temporary assignment to stabilise and improve a busy frontline customer services function.',
    postedAt: daysAgo(3),
  },
  {
    id: 'job-19',
    title: 'Head of Finance',
    organisation: 'Milton Keynes Council',
    location: 'Milton Keynes',
    region: 'Buckinghamshire',
    salary: '£78,000 – £92,000',
    salaryMin: 78000,
    salaryMax: 92000,
    contractType: 'Permanent',
    sector: 'Local government',
    description:
      'Lead corporate finance, budget setting and medium-term financial strategy for a unitary authority.',
    postedAt: daysAgo(4),
  },
  {
    id: 'job-20',
    title: 'Business Analyst',
    organisation: 'Suffolk Constabulary',
    location: 'Ipswich',
    region: 'Suffolk',
    salary: '£40,000 – £46,000',
    salaryMin: 40000,
    salaryMax: 46000,
    contractType: 'Interim',
    sector: 'Emergency services',
    description:
      'Interim analyst role supporting a force-wide programme to modernise frontline digital tooling.',
    postedAt: daysAgo(7),
  },
];

export const mockStaff: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Amara Okafor',
    title: 'Director of Public Sector',
    blurb:
      'Fifteen years placing senior policy and strategy leaders across UK local and central government.',
    yearsExperience: 15,
    qualification: 'MCIPD',
    area: 'National',
  },
  {
    id: 'staff-2',
    name: 'Rhys Llewellyn',
    title: 'Principal Consultant – Social Care',
    blurb:
      'Specialist in permanent and interim social care recruitment, with a focus on children and families.',
    yearsExperience: 11,
    qualification: 'REC CertRP',
    area: 'North & Midlands',
  },
  {
    id: 'staff-3',
    name: 'Hannah Patel',
    title: 'Senior Consultant – Planning & Regeneration',
    blurb:
      'Partners with councils and combined authorities to recruit planners, regeneration and housing professionals.',
    yearsExperience: 8,
    qualification: 'BA (Hons) Urban Planning',
    area: 'South East',
  },
  {
    id: 'staff-4',
    name: 'Daniel Ferreira',
    title: 'Consultant – Data & Digital',
    blurb:
      'Focused on data, digital and technology roles across public health, transport and central government.',
    yearsExperience: 6,
    qualification: 'BSc Computer Science',
    area: 'London & Remote',
  },
];
